namespace SecureIncidentHub.Application.Evidence;

/// <summary>
/// Application port. Callers must authorize tenant ownership first. Implementations must
/// fail if they cannot enforce the requested restrictions. No adapter exists in Phase 0.
/// </summary>
public interface IObjectStorage
{
    Task<UploadGrant> CreateUploadGrantAsync(UploadRequest request, CancellationToken cancellationToken);

    Task<DownloadGrant> CreateDownloadGrantAsync(
        ObjectReference reference, DateTimeOffset expiresAt, CancellationToken cancellationToken);
}

/// <summary>Opaque IDs generated by the server; never derived from a filename or browser path.</summary>
public sealed record ObjectReference(Guid OrganizationId, Guid ObjectId);

/// <summary>Exact content type and maximum bytes must be enforced by the future adapter.</summary>
public sealed record UploadRequest(
    ObjectReference Reference, long MaximumBytes, string ContentType, DateTimeOffset ExpiresAt);

/// <summary>Supports form POST or header-based upload grants without exposing provider SDK types.</summary>
public sealed record UploadGrant(
    Uri Url, string Method, IReadOnlyDictionary<string, string> Headers,
    IReadOnlyDictionary<string, string> FormFields, DateTimeOffset ExpiresAt);

/// <summary>A sensitive, short-lived capability. Never log or persist the URL.</summary>
public sealed record DownloadGrant(Uri Url, DateTimeOffset ExpiresAt);
