<Project Sdk="Microsoft.NET.Sdk.Worker">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="../SecureIncidentHub.Infrastructure/SecureIncidentHub.Infrastructure.csproj" />
        <PackageReference Include="Microsoft.Extensions.Hosting" />
    </ItemGroup>
</Project>
