<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
        <ProjectReference Include="../SecureIncidentHub.Application/SecureIncidentHub.Application.csproj" />
        <PackageReference Include="OpenTelemetry.Extensions.Hosting" />
        <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" />
        <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" />
    </ItemGroup>
</Project>
